-- SDKWork cms consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_cms_legacy_baseline.sql
-- Consolidated legacy baseline for sdkwork-cms database module.
-- Review and replace with contract-first migrations.

-- source: crates/sdkwork-content-cms-repository-sqlx/migrations/0001_cms_v1_foundation.sql
-- SDKWork CMS v1 foundation schema.
-- Target dialect: PostgreSQL.
-- Logical contract follows sdkwork-specs/DATABASE_SPEC.md.
-- TODO: Wire this migration into the repository migration runner before executing against any database.

CREATE TABLE IF NOT EXISTS cms_site (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 2,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    description TEXT,
    default_locale VARCHAR(32) NOT NULL DEFAULT 'en-US',
    default_channel_id BIGINT,
    domain_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    locale_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    publish_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT uk_cms_site_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT ck_cms_site_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_channel (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    channel_kind VARCHAR(64) NOT NULL,
    delivery_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    visibility_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    sort_order INTEGER NOT NULL DEFAULT 100,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT uk_cms_channel_site_code UNIQUE (tenant_id, site_id, code),
    CONSTRAINT ck_cms_channel_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_content_type (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    content_kind VARCHAR(64) NOT NULL DEFAULT 'entry',
    description TEXT,
    icon VARCHAR(128),
    schema_version BIGINT NOT NULL DEFAULT 1,
    workflow_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    default_body_format VARCHAR(64) NOT NULL DEFAULT 'blocks',
    settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT uk_cms_content_type_site_code UNIQUE (tenant_id, site_id, code),
    CONSTRAINT ck_cms_content_type_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_content_field (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    content_type_id BIGINT NOT NULL REFERENCES cms_content_type(id) ON DELETE CASCADE,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    field_kind VARCHAR(64) NOT NULL,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    localized BOOLEAN NOT NULL DEFAULT FALSE,
    multiple BOOLEAN NOT NULL DEFAULT FALSE,
    searchable BOOLEAN NOT NULL DEFAULT FALSE,
    filterable BOOLEAN NOT NULL DEFAULT FALSE,
    sortable BOOLEAN NOT NULL DEFAULT FALSE,
    validation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    options_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    ui_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    default_value_json JSONB NOT NULL DEFAULT 'null'::jsonb,
    sort_order INTEGER NOT NULL DEFAULT 100,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT uk_cms_content_field_code UNIQUE (tenant_id, content_type_id, code),
    CONSTRAINT ck_cms_content_field_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_taxonomy (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    taxonomy_kind VARCHAR(64) NOT NULL,
    description TEXT,
    settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT uk_cms_taxonomy_site_code UNIQUE (tenant_id, site_id, code),
    CONSTRAINT ck_cms_taxonomy_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_taxonomy_term (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    taxonomy_id BIGINT NOT NULL REFERENCES cms_taxonomy(id) ON DELETE CASCADE,
    parent_id BIGINT,
    code VARCHAR(128) NOT NULL,
    slug VARCHAR(256) NOT NULL,
    name VARCHAR(256) NOT NULL,
    description TEXT,
    path VARCHAR(1024) NOT NULL,
    level_no INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 100,
    seo_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT fk_cms_taxonomy_term_parent FOREIGN KEY (parent_id) REFERENCES cms_taxonomy_term(id) ON DELETE SET NULL,
    CONSTRAINT uk_cms_taxonomy_term_code UNIQUE (tenant_id, taxonomy_id, code),
    CONSTRAINT uk_cms_taxonomy_term_slug UNIQUE (tenant_id, taxonomy_id, slug),
    CONSTRAINT ck_cms_taxonomy_term_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_entry (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    content_type_id BIGINT NOT NULL REFERENCES cms_content_type(id),
    channel_id BIGINT REFERENCES cms_channel(id) ON DELETE SET NULL,
    primary_locale VARCHAR(32) NOT NULL DEFAULT 'en-US',
    locale VARCHAR(32) NOT NULL DEFAULT 'en-US',
    translation_group_id BIGINT,
    title VARCHAR(512) NOT NULL,
    slug VARCHAR(512) NOT NULL,
    summary TEXT,
    author_user_id BIGINT NOT NULL DEFAULT 0,
    owner_user_id BIGINT NOT NULL DEFAULT 0,
    entry_status INTEGER NOT NULL DEFAULT 0,
    publication_status INTEGER NOT NULL DEFAULT 0,
    current_version_id BIGINT,
    published_version_id BIGINT,
    first_published_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    scheduled_publish_at TIMESTAMPTZ,
    scheduled_unpublish_at TIMESTAMPTZ,
    seo_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    extra_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    data_scope INTEGER NOT NULL DEFAULT 2,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT uk_cms_entry_site_slug_locale UNIQUE (tenant_id, site_id, channel_id, locale, slug),
    CONSTRAINT ck_cms_entry_status CHECK (entry_status IN (0, 10, 20, 30, 40, 9)),
    CONSTRAINT ck_cms_entry_publication_status CHECK (publication_status IN (0, 10, 20, 30, 40))
);

CREATE TABLE IF NOT EXISTS cms_entry_body (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    entry_id BIGINT NOT NULL REFERENCES cms_entry(id) ON DELETE CASCADE,
    locale VARCHAR(32) NOT NULL DEFAULT 'en-US',
    body_format VARCHAR(64) NOT NULL DEFAULT 'blocks',
    body_text TEXT,
    body_html TEXT,
    block_tree_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    plain_text TEXT,
    checksum VARCHAR(128),
    word_count INTEGER NOT NULL DEFAULT 0,
    reading_time_seconds INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cms_entry_body_entry_locale UNIQUE (entry_id, locale)
);

CREATE TABLE IF NOT EXISTS cms_entry_field_value (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    entry_id BIGINT NOT NULL REFERENCES cms_entry(id) ON DELETE CASCADE,
    field_id BIGINT NOT NULL REFERENCES cms_content_field(id) ON DELETE CASCADE,
    locale VARCHAR(32) NOT NULL DEFAULT 'default',
    value_text TEXT,
    value_number NUMERIC(30, 8),
    value_boolean BOOLEAN,
    value_datetime TIMESTAMPTZ,
    value_json JSONB NOT NULL DEFAULT 'null'::jsonb,
    value_ref_type VARCHAR(64),
    value_ref_id BIGINT,
    search_text TEXT,
    sort_order INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cms_entry_field_value_unique UNIQUE (entry_id, field_id, locale, sort_order)
);

CREATE TABLE IF NOT EXISTS cms_entry_version (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    entry_id BIGINT NOT NULL REFERENCES cms_entry(id) ON DELETE CASCADE,
    version_no BIGINT NOT NULL,
    version_kind VARCHAR(64) NOT NULL DEFAULT 'draft',
    title_snapshot VARCHAR(512) NOT NULL,
    schema_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    content_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    media_snapshot_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    term_snapshot_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    checksum VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cms_entry_version_no UNIQUE (entry_id, version_no)
);

CREATE TABLE IF NOT EXISTS cms_entry_media (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    entry_id BIGINT NOT NULL REFERENCES cms_entry(id) ON DELETE CASCADE,
    field_id BIGINT REFERENCES cms_content_field(id) ON DELETE SET NULL,
    media_role VARCHAR(64) NOT NULL,
    drive_space_id VARCHAR(64),
    drive_node_id VARCHAR(64),
    drive_uri VARCHAR(512),
    media_resource_id VARCHAR(128),
    media_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    alt_text VARCHAR(512),
    caption VARCHAR(1024),
    sort_order INTEGER NOT NULL DEFAULT 100,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_cms_entry_media_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_entry_term (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    entry_id BIGINT NOT NULL REFERENCES cms_entry(id) ON DELETE CASCADE,
    taxonomy_id BIGINT NOT NULL REFERENCES cms_taxonomy(id) ON DELETE CASCADE,
    term_id BIGINT NOT NULL REFERENCES cms_taxonomy_term(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cms_entry_term UNIQUE (entry_id, term_id)
);

CREATE TABLE IF NOT EXISTS cms_page (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    channel_id BIGINT REFERENCES cms_channel(id) ON DELETE SET NULL,
    locale VARCHAR(32) NOT NULL DEFAULT 'en-US',
    parent_id BIGINT,
    path VARCHAR(1024) NOT NULL,
    slug VARCHAR(512) NOT NULL,
    title VARCHAR(512) NOT NULL,
    page_kind VARCHAR(64) NOT NULL DEFAULT 'page',
    template_code VARCHAR(128),
    publication_status INTEGER NOT NULL DEFAULT 0,
    published_snapshot_id BIGINT,
    seo_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT fk_cms_page_parent FOREIGN KEY (parent_id) REFERENCES cms_page(id) ON DELETE SET NULL,
    CONSTRAINT uk_cms_page_path UNIQUE (tenant_id, site_id, channel_id, locale, path),
    CONSTRAINT ck_cms_page_status CHECK (status IN (0, 1, 2, 9)),
    CONSTRAINT ck_cms_page_publication_status CHECK (publication_status IN (0, 10, 20, 30, 40))
);

CREATE TABLE IF NOT EXISTS cms_page_block (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    page_id BIGINT NOT NULL REFERENCES cms_page(id) ON DELETE CASCADE,
    parent_block_id BIGINT,
    slot_code VARCHAR(128) NOT NULL DEFAULT 'main',
    block_code VARCHAR(128) NOT NULL,
    block_kind VARCHAR(64) NOT NULL,
    ref_type VARCHAR(64),
    ref_id BIGINT,
    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    sort_order INTEGER NOT NULL DEFAULT 100,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_cms_page_block_parent FOREIGN KEY (parent_block_id) REFERENCES cms_page_block(id) ON DELETE CASCADE,
    CONSTRAINT ck_cms_page_block_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_publish_snapshot (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    owner_type VARCHAR(64) NOT NULL,
    owner_id BIGINT NOT NULL,
    version_id BIGINT,
    channel_id BIGINT REFERENCES cms_channel(id) ON DELETE SET NULL,
    locale VARCHAR(32) NOT NULL DEFAULT 'default',
    snapshot_version BIGINT NOT NULL DEFAULT 1,
    snapshot_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    cache_tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    checksum VARCHAR(128),
    status INTEGER NOT NULL DEFAULT 1,
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_by BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cms_publish_snapshot_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_feed (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    channel_id BIGINT REFERENCES cms_channel(id) ON DELETE SET NULL,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    feed_kind VARCHAR(64) NOT NULL DEFAULT 'hybrid',
    locale VARCHAR(32) NOT NULL DEFAULT 'default',
    default_page_size INTEGER NOT NULL DEFAULT 20,
    ranking_profile_ref VARCHAR(128),
    rule_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    published_snapshot_id BIGINT,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT uk_cms_feed_site_code UNIQUE (tenant_id, site_id, channel_id, locale, code),
    CONSTRAINT ck_cms_feed_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_feed_rule (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    feed_id BIGINT NOT NULL REFERENCES cms_feed(id) ON DELETE CASCADE,
    rule_kind VARCHAR(64) NOT NULL,
    content_type_id BIGINT REFERENCES cms_content_type(id) ON DELETE SET NULL,
    taxonomy_id BIGINT REFERENCES cms_taxonomy(id) ON DELETE SET NULL,
    taxonomy_term_id BIGINT REFERENCES cms_taxonomy_term(id) ON DELETE SET NULL,
    q VARCHAR(512),
    condition_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    sort_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    limit_count INTEGER NOT NULL DEFAULT 50,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cms_feed_item (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    feed_id BIGINT NOT NULL REFERENCES cms_feed(id) ON DELETE CASCADE,
    entry_id BIGINT REFERENCES cms_entry(id) ON DELETE SET NULL,
    page_id BIGINT REFERENCES cms_page(id) ON DELETE SET NULL,
    external_url VARCHAR(2048),
    item_kind VARCHAR(64) NOT NULL DEFAULT 'entry',
    position_no INTEGER,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    operator_title VARCHAR(512),
    operator_summary TEXT,
    operator_media_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    sort_order INTEGER NOT NULL DEFAULT 100,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_cms_feed_item_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_feed_snapshot (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL REFERENCES cms_site(id) ON DELETE CASCADE,
    feed_id BIGINT NOT NULL REFERENCES cms_feed(id) ON DELETE CASCADE,
    publish_snapshot_id BIGINT REFERENCES cms_publish_snapshot(id) ON DELETE SET NULL,
    snapshot_version BIGINT NOT NULL DEFAULT 1,
    item_count INTEGER NOT NULL DEFAULT 0,
    items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    rule_summary_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    checksum VARCHAR(128),
    status INTEGER NOT NULL DEFAULT 1,
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_by BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cms_feed_snapshot_status CHECK (status IN (0, 1, 2, 9))
);

CREATE TABLE IF NOT EXISTS cms_audit_log (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT,
    actor_user_id BIGINT NOT NULL DEFAULT 0,
    action VARCHAR(128) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id BIGINT,
    resource_uuid VARCHAR(64),
    before_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    request_id VARCHAR(128),
    trace_id VARCHAR(128),
    ip_address VARCHAR(128),
    user_agent VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cms_outbox_event (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    event_version INTEGER NOT NULL DEFAULT 1,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    headers_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status INTEGER NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    error_message TEXT,
    request_id VARCHAR(128),
    trace_id VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cms_outbox_event_status CHECK (status IN (0, 1, 2, 3, 9))
);

CREATE TABLE IF NOT EXISTS cms_idempotency_key (
    id BIGINT PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    principal_type VARCHAR(64) NOT NULL,
    principal_id BIGINT NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(256) NOT NULL,
    method VARCHAR(16) NOT NULL,
    path VARCHAR(1024) NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    response_status INTEGER,
    response_body_json JSONB,
    resource_type VARCHAR(64),
    resource_id BIGINT,
    status INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cms_idempotency_key UNIQUE (tenant_id, principal_type, principal_id, method, path, idempotency_key),
    CONSTRAINT ck_cms_idempotency_status CHECK (status IN (0, 1, 2, 3))
);

ALTER TABLE cms_site
    ADD CONSTRAINT fk_cms_site_default_channel
    FOREIGN KEY (default_channel_id) REFERENCES cms_channel(id) ON DELETE SET NULL;

ALTER TABLE cms_entry
    ADD CONSTRAINT fk_cms_entry_current_version
    FOREIGN KEY (current_version_id) REFERENCES cms_entry_version(id) ON DELETE SET NULL;

ALTER TABLE cms_entry
    ADD CONSTRAINT fk_cms_entry_published_version
    FOREIGN KEY (published_version_id) REFERENCES cms_entry_version(id) ON DELETE SET NULL;

ALTER TABLE cms_page
    ADD CONSTRAINT fk_cms_page_published_snapshot
    FOREIGN KEY (published_snapshot_id) REFERENCES cms_publish_snapshot(id) ON DELETE SET NULL;

ALTER TABLE cms_feed
    ADD CONSTRAINT fk_cms_feed_published_snapshot
    FOREIGN KEY (published_snapshot_id) REFERENCES cms_feed_snapshot(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_cms_site_tenant_status ON cms_site (tenant_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_channel_site_status ON cms_channel (tenant_id, site_id, status, sort_order);
CREATE INDEX IF NOT EXISTS idx_cms_content_type_site_status ON cms_content_type (tenant_id, site_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_content_field_type_order ON cms_content_field (tenant_id, content_type_id, status, sort_order);
CREATE INDEX IF NOT EXISTS idx_cms_taxonomy_site_status ON cms_taxonomy (tenant_id, site_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_taxonomy_term_tree ON cms_taxonomy_term (tenant_id, taxonomy_id, parent_id, status, sort_order);
CREATE INDEX IF NOT EXISTS idx_cms_taxonomy_term_path ON cms_taxonomy_term (tenant_id, taxonomy_id, path);

CREATE INDEX IF NOT EXISTS idx_cms_entry_list ON cms_entry (tenant_id, site_id, content_type_id, entry_status, publication_status, updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_cms_entry_published ON cms_entry (tenant_id, site_id, channel_id, locale, publication_status, published_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_cms_entry_author ON cms_entry (tenant_id, site_id, author_user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_entry_schedule ON cms_entry (tenant_id, publication_status, scheduled_publish_at, scheduled_unpublish_at);
CREATE INDEX IF NOT EXISTS idx_cms_entry_translation ON cms_entry (tenant_id, translation_group_id, locale);
CREATE INDEX IF NOT EXISTS idx_cms_entry_body_entry ON cms_entry_body (entry_id, locale);
CREATE INDEX IF NOT EXISTS idx_cms_entry_field_value_field_text ON cms_entry_field_value (tenant_id, field_id, locale, value_text);
CREATE INDEX IF NOT EXISTS idx_cms_entry_field_value_field_number ON cms_entry_field_value (tenant_id, field_id, value_number);
CREATE INDEX IF NOT EXISTS idx_cms_entry_field_value_field_datetime ON cms_entry_field_value (tenant_id, field_id, value_datetime);
CREATE INDEX IF NOT EXISTS idx_cms_entry_version_entry ON cms_entry_version (entry_id, version_no DESC);
CREATE INDEX IF NOT EXISTS idx_cms_entry_media_entry_role ON cms_entry_media (tenant_id, entry_id, media_role, sort_order);
CREATE INDEX IF NOT EXISTS idx_cms_entry_media_drive_node ON cms_entry_media (tenant_id, drive_node_id);
CREATE INDEX IF NOT EXISTS idx_cms_entry_term_term ON cms_entry_term (tenant_id, term_id, entry_id);

CREATE INDEX IF NOT EXISTS idx_cms_page_route ON cms_page (tenant_id, site_id, channel_id, locale, path, status);
CREATE INDEX IF NOT EXISTS idx_cms_page_parent ON cms_page (tenant_id, site_id, parent_id, status);
CREATE INDEX IF NOT EXISTS idx_cms_page_block_page_slot ON cms_page_block (tenant_id, page_id, slot_code, sort_order);
CREATE INDEX IF NOT EXISTS idx_cms_page_block_ref ON cms_page_block (tenant_id, ref_type, ref_id);

CREATE INDEX IF NOT EXISTS idx_cms_publish_snapshot_owner ON cms_publish_snapshot (tenant_id, site_id, owner_type, owner_id, status, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_publish_snapshot_channel ON cms_publish_snapshot (tenant_id, site_id, channel_id, locale, status, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_cms_feed_site_status ON cms_feed (tenant_id, site_id, channel_id, locale, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_feed_rule_feed ON cms_feed_rule (tenant_id, feed_id, enabled, sort_order);
CREATE INDEX IF NOT EXISTS idx_cms_feed_item_feed_order ON cms_feed_item (tenant_id, feed_id, status, pinned DESC, position_no, sort_order);
CREATE INDEX IF NOT EXISTS idx_cms_feed_item_entry ON cms_feed_item (tenant_id, entry_id);
CREATE INDEX IF NOT EXISTS idx_cms_feed_snapshot_feed ON cms_feed_snapshot (tenant_id, feed_id, status, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_cms_audit_log_resource ON cms_audit_log (tenant_id, site_id, resource_type, resource_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_audit_log_actor ON cms_audit_log (tenant_id, actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_outbox_event_pending ON cms_outbox_event (status, next_attempt_at, created_at);
CREATE INDEX IF NOT EXISTS idx_cms_outbox_event_aggregate ON cms_outbox_event (tenant_id, aggregate_type, aggregate_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_idempotency_expiry ON cms_idempotency_key (expires_at, status);

COMMENT ON TABLE cms_site IS 'CMS site/workspace boundary. Owns site settings, locale config, domain config, and publish defaults.';
COMMENT ON TABLE cms_channel IS 'CMS delivery channel such as web, app, h5, mini_program, rss, or api.';
COMMENT ON TABLE cms_content_type IS 'CMS content model definition.';
COMMENT ON TABLE cms_content_field IS 'CMS content model field definition, including validation, options, search flags, and UI config.';
COMMENT ON TABLE cms_taxonomy IS 'CMS taxonomy group such as category, tag, topic, or audience.';
COMMENT ON TABLE cms_taxonomy_term IS 'CMS taxonomy term tree.';
COMMENT ON TABLE cms_entry IS 'CMS content entry aggregate root.';
COMMENT ON TABLE cms_entry_body IS 'CMS content body and block tree.';
COMMENT ON TABLE cms_entry_field_value IS 'CMS dynamic field value table for filterable and searchable custom fields.';
COMMENT ON TABLE cms_entry_version IS 'CMS immutable content version snapshot.';
COMMENT ON TABLE cms_entry_media IS 'CMS entry media relation. Stores Drive references and media snapshots only.';
COMMENT ON TABLE cms_entry_term IS 'CMS entry to taxonomy term relation.';
COMMENT ON TABLE cms_page IS 'CMS page route and page-level SEO/publish metadata.';
COMMENT ON TABLE cms_page_block IS 'CMS page composition block.';
COMMENT ON TABLE cms_publish_snapshot IS 'CMS unified published snapshot for entries, pages, feeds, and future publishable owners.';
COMMENT ON TABLE cms_feed IS 'CMS feed definition for curated, rule, hybrid, search, recommendation, or rss feed lines.';
COMMENT ON TABLE cms_feed_rule IS 'CMS feed automatic rule definition.';
COMMENT ON TABLE cms_feed_item IS 'CMS feed manual curated item.';
COMMENT ON TABLE cms_feed_snapshot IS 'CMS feed published item snapshot for stable delivery.';
COMMENT ON TABLE cms_audit_log IS 'CMS business audit log.';
COMMENT ON TABLE cms_outbox_event IS 'CMS durable outbox event table.';
COMMENT ON TABLE cms_idempotency_key IS 'CMS idempotent command record.';
